services:
  - type: web
    name: ai-video-summarizer
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: TOKENIZERS_PARALLELISM
        value: "false"